from typing import Any
from NVDAObjects import NVDAObject
from textInfos import TextInfo

class AppModule:
	processID: int
	def __init__(self, *args: Any, **kwargs: Any) -> None: ...
	def chooseNVDAObjectOverlayClasses(self, obj: NVDAObject, clsList: list[type[NVDAObject]]) -> None: ...
	def _get_statusBar(self) -> NVDAObject | None: ...
	def getStatusBarText(self, obj: NVDAObject) -> str: ...
	def _get_statusBarTextInfo(self) -> TextInfo | None: ...
	def terminate(self) -> None: ...
