from typing import Any
from NVDAObjects import NVDAObject

class AppModule:
    processID: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def chooseNVDAObjectOverlayClasses(self, obj: NVDAObject, clsList: list[type[NVDAObject]]) -> None: ...
    def terminate(self) -> None: ...
