ES_MULTILINE: int
GW_HWNDNEXT: int
OBJID_CLIENT: int
GA_ROOT: int

def getAncestor(hwnd: int, flags: int) -> int: ...
def getForegroundWindow() -> int: ...
def getWindowThreadProcessID(hwnd: int) -> tuple[int, int]: ...
def getTopWindow(hwnd: int) -> int: ...
def getWindow(hwnd: int, relation: int) -> int: ...
def isWindowVisible(hwnd: int) -> bool: ...
def getClassName(hwnd: int) -> str: ...
