from collections.abc import Callable

VERTICAL: int

class Window: ...
class Control(Window): ...
class Panel(Window): ...
class Sizer: ...

class StaticBoxSizer(Sizer):
	def __init__(self, orient: int, parent: Window, label: str) -> None: ...

class Choice(Control):
	def SetSelection(self, value: int) -> None: ...
	def GetSelection(self) -> int: ...

class PyTimer:
	def __init__(self, callback: Callable[[], None]) -> None: ...
	def Start(self, milliseconds: int) -> bool: ...
	def Stop(self) -> None: ...
