from typing import Any
import wx

class BoxSizerHelper:
    def __init__(self, parent: wx.Window, sizer: wx.Sizer) -> None: ...
    def addLabeledControl[T: wx.Control](self, labelText: str, wxCtrlClass: type[T], **kwargs: Any) -> T: ...
    def addItem(self, item: wx.Sizer) -> Any: ...
