from NVDAObjects import NVDAObject

class LiveText(NVDAObject):
    _keepMonitoring: bool
    def initOverlayClass(self) -> None: ...
    def startMonitoring(self) -> None: ...
    def stopMonitoring(self) -> None: ...
    def event_textChange(self) -> None: ...
    def _getText(self) -> str: ...
    def _calculateNewText(self, newText: str, oldText: str) -> list[str]: ...
    def _reportNewLines(self, lines: list[str]) -> None: ...
    def _reportNewText(self, line: str) -> None: ...
